repos:
  - repo: https://github.com/ambv/black
    rev: 23.9.0
    hooks:
    - id: black
      args: [--line-length=120]
      language_version: python3.10
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.287
    hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
